Aplikacja do pytań
hudyweas/Projekt1 pull request #1
Opened 2020-10-29 16:19 UTC by hudyweas

2020-10-29 16:24 UTC, piszu commented
Należy utworzyć .gitignore z zasadami dla eclipse i intelij
Można uporządkować  commity, żeby nie było w nich bałaganu i nie wnoszacych nic  komentarzy

2020-10-29 16:32 UTC, piszu requested changes

2020-10-29 16:32 UTC, piszu commented on questions.txt
> +Abfegr;tak:1;oczywiście:1;nie:0;bardzo:1
Trochę brakuje nagłówka, więc nie do końca wiadomo, co jest czym tutaj.

2020-10-29 16:32 UTC, piszu commented on src/DataBase.java
> +import java.util.ArrayList;
Należy uporządkować importy, najlepiej poprzez reguły formatowania w IDE.
Jeśli importujemy z tego samego katalogu, to po 3/5 takich samych importach powinniśmy przerzucić się na *.

2020-10-29 16:32 UTC, piszu commented on src/DataBase.java
> +	private void deleteQuestion(int x) { //usuwa wybrane pytanie z listy
Skoro metoda nazywa się deleteQuestion to znaczy, że wiemy, co robi, raczej nie trzeba dodawać komentarza.
W innych podobnie. Ewentualnie można zmienić na deleteQuestionByPlaceNumber czy cos w tym stylu.

2020-10-29 16:32 UTC, piszu commented on src/Program.java
> +				+ "2. Test sk�ada si� z 20 pyta�"
Kodowanie :)

2020-10-29 16:32 UTC, piszu commented on src/Program.java
> +	private int licznik = 0;
Język zmiennych

2020-10-29 16:32 UTC, piszu commented on src/Program.java
> +			getQuestion();
getQuestion powinno pobrać pytanie do jakiejś zmiennej, natomiast display powinno wyświetlić zadane pytanie.
`licznik` nie powinien być współdzielony przez metody, bo jest to robione niejawnie.
A co jeśli chciałbym dla odmiany pobrać pytanie w innej metodzie? I nie pierwsze, a 13?

2020-10-31 10:59 UTC, hudyweas commented on questions.txt
> +Abfegr;tak:1;oczywiście:1;nie:0;bardzo:1
Pytanie;odpowiedź1;odpowiedź2;odpowiedź3;odpowiedź4

1-prawda
0-fałsz

2020-10-31 11:00 UTC, hudyweas commented on src/Program.java
> +				+ "2. Test sk�ada si� z 20 pyta�"
Nie bardzo rozumiem co tutaj rozumiesz przez kodowanie

2020-10-31 11:08 UTC, hudyweas commented on src/Program.java
> +			getQuestion();
I tak właśnie jest. getQuestion pobiera Stringa z bazy oraz rozbija go na pytanie oraz odpowiedzi. Pytanie jest zapisywane w zmiennej currentQuestion, a odpowiedzi są rozbijane jeszcze na odpowiedź, która jest wyświetlana w zmiennej currentAnswers oraz na informacje, czy ta odpowiedź jest prawidłowa. To jest zapisywane w zmiennej currentGoodAnswers pod tym samym indeksem co odpowiedź.

Faktycznie nie mógłbyś podczas odpowiedzi na pytanie 1 pobrać pytania 13, ponieważ program ma zapisane tylko jedno pytanie, które nie jest zapisywane, lecz przy pobieraniu kolejnego jest nadpisywane. Zrobiłem to, by oszczędzać miejsce w pamięci, ale faktycznie może to ograniczać później rozwinięcie programu

2020-10-31 11:37 UTC, merged