update 6/11/2020
hudyweas/Projekt1 pull request #3
Opened 2020-11-06 14:12 UTC by hudyweas

2020-11-07 13:59 UTC, piszu requested changes

2020-11-07 13:59 UTC, piszu commented on src/Program.java
> +
do do, da da.
To jest super nieczytelne i nie do końca po pierwszym spojrzeniu na to wiadomo, co się tutaj dzieje tak w ogóle.
Jedna pętla jest tutaj całkowicie zbędna w mojej opinii.

Rzuć okiem na to:
https://stackoverflow.com/questions/19925047/how-to-check-the-input-is-an-integer-or-not-in-java

Zmienne 
        `String numberOfQuestionsString;`
        `int numberOfQuestions;`
Są nadmiarowe.

2020-11-07 13:59 UTC, piszu commented on src/Program.java
> +        int points = 0;;
Dwa średniki.

2020-11-07 13:59 UTC, piszu commented on src/Program.java
> +        string = string.toLowerCase();
Spoko przeniesienie. Tutaj i tak ta metoda do przemyślenia, bo co, jeśli będzie 3 lub 5 odpowiedzi?

2020-11-07 13:59 UTC, piszu commented on src/Program.java
> +        int points = 0;;
Variable 'points' is never used

2020-11-07 13:59 UTC, piszu commented on src/Program.java
Field 'dataBase' may be 'final'

2020-11-07 13:59 UTC, piszu commented on src/Program.java
>                  while(isOneOfStrings(userInput, "x", "a", "b", "c", "d") == false){
Czytaj podpowiedzi z IDE, jest ich jeszcze kilka :) 

`'isOneOfStrings(userInput, "x", "a", "b", "c", "d") == false' can be simplified to '!isOneOfStrings(userInput, "x", "a", "b", "c", "d")'`

2020-11-07 13:59 UTC, piszu commented on src/Question.java
>      public boolean isHasBeenUsed() {
A nie czytelniej->  isUsed?

2020-11-07 19:38 UTC, hudyweas commented on src/Question.java
>      public boolean isHasBeenUsed() {
racja, zrobiłem automatycznie ten getter

2020-11-08 09:18 UTC, piszu requested changes

2020-11-08 09:18 UTC, piszu commented on src/Answer.java
>      private boolean isAnswerApproved = false;
Answer.isAnswerApproved
Answer.isItCorrectAnswer

2020-11-08 09:18 UTC, piszu commented on src/Program.java
> +        return !switch (NoOfAnswers) {
Zmienna, więc raczej małą literą.

2020-11-08 22:49 UTC, piszu approved these changes
Niech będzie jak jest. Approve.

2020-11-14 15:14 UTC, piszu requested changes

2020-11-14 15:14 UTC, piszu commented on src/Answer.java
Niepotrzebna wolna linia. Formatter.

2020-11-14 15:14 UTC, piszu commented on src/Answer.java
> +        if(isApproved = false)
Co na tę linię mówi intelij?

2020-11-14 15:14 UTC, piszu commented on src/Program.java
>      private boolean isOneOfStrings(String string, String... args){
Chyba teraz nieużywamy? Remove.

2020-11-14 15:14 UTC, piszu commented on src/Program.java
> +        for(int letterIndex = 0; letterIndex < letters.length; letterIndex++){
W ogóle tutaj jest wymyślenie koła na nowo.
Poczytaj o Array and ArrayList.

2020-11-14 15:14 UTC, piszu commented on src/Program.java
> +        List<Question> questions = new ArrayList<>();
`userQuestions` ?

2020-11-16 13:02 UTC, piszu approved these changes

2020-11-16 13:02 UTC, closed without merging